# Generated by Django 5.1.3 on 2024-11-24 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mama',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcionMama', models.TextField()),
                ('imagenSintoma', models.ImageField(blank=True, null=True, upload_to='sintomas/')),
                ('descripcionSintoma', models.TextField()),
            ],
        ),
    ]
