# Generated by Django 5.1.3 on 2024-11-24 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bebe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagenBebe', models.ImageField(blank=True, null=True, upload_to='bebes/')),
                ('descripcionBebe', models.TextField()),
                ('imagenFruta', models.ImageField(blank=True, null=True, upload_to='frutas/')),
                ('descripcionFruta', models.TextField()),
            ],
        ),
    ]
